version: '3'
services:
  sensor-config-backend:
    image: sensor-config-backend:latest
    restart: always
    ports:
      - "13337:13337"
  sensor-config-frontend:
    stdin_open: true
    image: sensor-config-frontend:latest
    restart: always
    ports:
      - "3000:3000"